# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.view_tab = QtWidgets.QWidget()
        self.view_tab.setObjectName("view_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.view_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.controls_frame = QtWidgets.QFrame(self.view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controls_frame.sizePolicy().hasHeightForWidth())
        self.controls_frame.setSizePolicy(sizePolicy)
        self.controls_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controls_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controls_frame.setObjectName("controls_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.controls_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.control_label = QtWidgets.QLabel(self.controls_frame)
        self.control_label.setObjectName("control_label")
        self.horizontalLayout_2.addWidget(self.control_label)
        self.control_spinbox = QtWidgets.QDoubleSpinBox(self.controls_frame)
        self.control_spinbox.setObjectName("control_spinbox")
        self.horizontalLayout_2.addWidget(self.control_spinbox)
        self.control_slider = QtWidgets.QSlider(self.controls_frame)
        self.control_slider.setMaximum(100)
        self.control_slider.setOrientation(QtCore.Qt.Horizontal)
        self.control_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.control_slider.setObjectName("control_slider")
        self.horizontalLayout_2.addWidget(self.control_slider)
        self.verticalLayout_2.addWidget(self.controls_frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.view_frame = QtWidgets.QFrame(self.view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_frame.sizePolicy().hasHeightForWidth())
        self.view_frame.setSizePolicy(sizePolicy)
        self.view_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.view_frame.setObjectName("view_frame")
        self.horizontalLayout.addWidget(self.view_frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.view_tab, "")
        self.plots_tab = QtWidgets.QWidget()
        self.plots_tab.setObjectName("plots_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.plots_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.plots_tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.tabWidget.addTab(self.plots_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 35))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOrbit = QtWidgets.QMenu(self.menubar)
        self.menuOrbit.setObjectName("menuOrbit")
        self.menuSimulation = QtWidgets.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoadCsv = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionLoadCsv.setIcon(icon)
        self.actionLoadCsv.setObjectName("actionLoadCsv")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionRun = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.actionRun.setIcon(icon)
        self.actionRun.setObjectName("actionRun")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("media-playback-pause")
        self.actionPause.setIcon(icon)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("media-playback-stop")
        self.actionStop.setIcon(icon)
        self.actionStop.setObjectName("actionStop")
        self.actionGeneratePlot = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("go-bottom")
        self.actionGeneratePlot.setIcon(icon)
        self.actionGeneratePlot.setObjectName("actionGeneratePlot")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoadCsv)
        self.menuFile.addAction(self.actionExit)
        self.menuSimulation.addAction(self.actionRun)
        self.menuSimulation.addAction(self.actionPause)
        self.menuSimulation.addAction(self.actionStop)
        self.menuData.addAction(self.actionGeneratePlot)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOrbit.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionLoadCsv)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionStop)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spacecraft Simulator Viewer"))
        self.control_label.setText(_translate("MainWindow", "Time scale"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.view_tab), _translate("MainWindow", "3D view"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plots_tab), _translate("MainWindow", "Plots"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOrbit.setTitle(_translate("MainWindow", "Orbit"))
        self.menuSimulation.setTitle(_translate("MainWindow", "Simulation"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoadCsv.setText(_translate("MainWindow", "Load csv"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionGeneratePlot.setText(_translate("MainWindow", "Generate plot"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
